BUILD: allow building with the limited-api flag set
This is based on
https://github.com/mesonbuild/meson-python/issues/787#issuecomment-3271080130

The code is set up to allow the limited api flag to be set,
but it is off by fefault (I find the settings unclear, so I
am just following the suggested practice and hoping for the
best).

The version used for the limited api is hardcoded to '3.11'
as the limited_api_version variable in

    sherpa/meson.build
    extern/grplib-4.18/meson.build
    extern/stklib-4.18/meson.build

These will need updating when the minimum Python version is
changed.

With this you can build a "limited API" build like

    pip install . -Csetup-args=-Dpython.allow_limited_api=true
    pip install -e . --no-build-isolation -Csetup-args=-Dpython.allow_limited_api=true
    python -m build -Csetup-args=-Dpython.allow_limited_api=true

This creates ".abi3" labelled compiled code: e.g. for a macOS
installation (Python 3.14 but installed from a Python 3.11
wheel) we get:

% find $CONDA_PREFIX/lib/python3.14/site-packages/sherpa -name \*.so | sed -e "s|.*/sherpa|.../sherpa|"
.../sherpa/optmethods/_saoopt.abi3.so
.../sherpa/optmethods/_tstoptfct.abi3.so
.../sherpa/estmethods/_est_funcs.abi3.so
.../sherpa/utils/integration.abi3.so
.../sherpa/utils/_utils.abi3.so
.../sherpa/utils/_psf.abi3.so
.../sherpa/models/_modelfcts.abi3.so
.../sherpa/astro/utils/_pileup.abi3.so
.../sherpa/astro/utils/_wcs.abi3.so
.../sherpa/astro/utils/_region.abi3.so
.../sherpa/astro/utils/_utils.abi3.so
.../sherpa/astro/models/_modelfcts.abi3.so
.../sherpa/stats/_statfcts.abi3.so

As a test: with a Python 3.11 environment I ran

% python -m build --wheel -Csetup-args=-Dpython.allow_limited_api=true
% ls -l dist
total 10120
-rw-r--r--@ 1 burked  staff  5178462 Jul 16 15:42 sherpa-4.19.0.dev0-cp311-abi3-macosx_26_0_arm64.whl

then I installed this into a Python 3.14 environment:

% python --version
3.14.4
% pip install dist/sherpa-4.19.0.dev0-cp311-abi3-macosx_26_0_arm64.whl

and was able to run sherpa_test.

If the installation is done without setting the limited-api flag to
true then you get a "normal" version-specific installation:

% ls -l dist
total 20240
-rw-r--r--@ 1 burked  staff  5178462 Jul 16 15:42 sherpa-4.19.0.dev0-cp311-abi3-macosx_26_0_arm64.whl
-rw-r--r--@ 1 burked  staff  5179123 Jul 16 15:58 sherpa-4.19.0.dev0-cp311-cp311-macosx_26_0_arm64.whl

and then you can't install that into a Python 3.14 environment;

% pip install dist/sherpa-4.19.0.dev0-cp311-cp311-macosx_26_0_arm64.whl
ERROR: sherpa-4.19.0.dev0-cp311-cp311-macosx_26_0_arm64.whl is not a supported wheel on this platform.

The .so files have the "normal" (non-abi3 labels):

% find $CONDA_PREFIX/lib/python3.11/site-packages/sherpa -name \*.so | sed -e "s|.*/sherpa|.../sherpa|"
.../sherpa/optmethods/_tstoptfct.cpython-311-darwin.so
.../sherpa/optmethods/_saoopt.cpython-311-darwin.so
.../sherpa/estmethods/_est_funcs.cpython-311-darwin.so
.../sherpa/utils/_utils.cpython-311-darwin.so
.../sherpa/utils/integration.cpython-311-darwin.so
.../sherpa/utils/_psf.cpython-311-darwin.so
.../sherpa/models/_modelfcts.cpython-311-darwin.so
.../sherpa/astro/utils/_utils.cpython-311-darwin.so
.../sherpa/astro/utils/_wcs.cpython-311-darwin.so
.../sherpa/astro/utils/_pileup.cpython-311-darwin.so
.../sherpa/astro/utils/_region.cpython-311-darwin.so
.../sherpa/astro/models/_modelfcts.cpython-311-darwin.so
.../sherpa/stats/_statfcts.cpython-311-darwin.so