Modified region code to remove implicit prototype error
Changes to remove build error or clang:

     regparser.y:629:5: error: implicit declaration of function 'regYYrestart' is
      invalid in C99 [-Werror,-Wimplicit-function-declaration]

and remove the workaround added to docs/install.rst in #1142.

The changes coincide with CIAO region lib bug fix SL-251.