utils: remove unused and buggy printf routine
Although not explicitly marked as deprecated, trying to call the
printf routine would error out since `if_` is not defined:

   >>> utils.printf("x = %d %s", 23, "ccc")
   Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "/home/dburke/sherpa/sherpa-2/sherpa/utils/__init__.py", line 2576, in printf
       return if_(args, args[-1], format)
              ^^^
   NameError: name 'if_' is not defined

This symbol has never been defined in this module; or at least, it was
not present when this file was added to git in the first commit:

    111768eafea620bc8dfc8f5a1827b66bbf9f6dad