The CERN MINUIT optimization library is now a user option (ie, the user is responsible for installing iminuit).
(sherpa-dev)[dtn@newdevel12 basic]$ pip uninstall iminuit

(sherpa-dev)[dtn@newdevel12 basic]$ python
Python 2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 17:02:03)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> from sherpa.astro.ui import *
>>> print list_methods()
['gridsearch', 'levmar', 'moncar', 'neldermead', 'simplex']

(sherpa-dev)[dtn@newdevel12 basic]$ pip install iminuit
Collecting iminuit
Installing collected packages: iminuit
Successfully installed iminuit-1.2

(sherpa-dev)[dtn@newdevel12 basic]$ python
Python 2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 17:02:03)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> from sherpa.astro.ui import *
>>> print list_methods()
['gridsearch', 'levmar', 'minuit', 'moncar', 'neldermead', 'simplex']

Sherpa is shipped with all the functions and the starting par values as
defined in the paper:

  Moré, J.J., Garbow, B.S. and Hillstrom, K.E., "Algorithm 566: Fortran
  Subroutines for Testing Unconstrained Optimization Software.", ACM TOMS,
  VOL. 7, PAGES 14-41 AND 136-140, 1981

However, only 26 out of the 35 tests are used because they are the only
functions which can be solved by the core optimization methods (MonCar,
NelderMead, LevMar, I can't believe we ship the stupid gridsearch. At least
I didn't write it).  Actually, sherpa is shipped with more then the
aforementioned test functions but that is just details then you need to know.

Note, the file sherpa/optmethods/tests/test_optmethods.py has the following
lines:

        #
        # If the following lines are uncommented out, we get errors
        # when running the optimization test
        #
        # try:
        #     import iminuit
        #     self.tst(optfcts.midnight, name + '_minuit', fct, fmin,
        #              x0, xmin, xmax, iprint=iprint)
        # except ImportError:
        #     pass

intentionally commented out for the simple reason that if they are left in
then the standard optimization tests for the minuit algorithm fail on 5 out of
the standard 26 functions.

(sherpa-dev)[dtn@newdevel12 sherpa]$ python sherpa/optmethods/tests/test_optmethods.py
  Found 26/26 tests for sherpa.optmethods.tests.test_optmethods
FF.FF............E........
======================================================================
ERROR: test_linear_fullrank0cols0rows (sherpa.optmethods.tests.test_optmethods.test_optmethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/export/sherpa/sherpa/optmethods/tests/test_optmethods.py", line 293, in test_linear_fullrank0cols0rows
    xmin, xmax )
  File "/export/sherpa/sherpa/optmethods/tests/test_optmethods.py", line 48, in tst_all
    x0, xmin, xmax, iprint=iprint)
  File "/export/sherpa/sherpa/optmethods/tests/test_optmethods.py", line 54, in tst
    status, x, fval, msg, stuff = optmethod( fct, x0, xmin, xmax, maxfev=maxfev*len(x0))
  File "/export/sherpa/sherpa/optmethods/optfcts.py", line 916, in midnight
    covar_matrix = numpy.array(myminuit.matrix(correlation=True))
  File "iminuit/_libiminuit.pyx", line 543, in iminuit._libiminuit.Minuit.matrix (iminuit/_libiminuit.cpp:7632)
RuntimeError: Covariance is not valid. May be the last Hesse call failed?

======================================================================
FAIL: test_bard (sherpa.optmethods.tests.test_optmethods.test_optmethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/export/sherpa/sherpa/optmethods/tests/test_optmethods.py", line 115, in test_bard
    self.tst_all( name, _tstoptfct.bard, fmin, x0, xmin, xmax )
  File "/export/sherpa/sherpa/optmethods/tests/test_optmethods.py", line 48, in tst_all
    x0, xmin, xmax, iprint=iprint)
  File "/export/sherpa/sherpa/optmethods/tests/test_optmethods.py", line 61, in tst
    self.assertEqualWithinTol( fval, fmin, self.tolerance )
  File "/export/sherpa/sherpa/utils/__init__.py", line 266, in assertEqualWithinTol
    self.assertFalse(numpy.any(sao_fcmp(first, second, tol)), msg)
AssertionError: True is not false

======================================================================
FAIL: test_beale (sherpa.optmethods.tests.test_optmethods.test_optmethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/export/sherpa/sherpa/optmethods/tests/test_optmethods.py", line 97, in test_beale
    self.tst_all( name,_tstoptfct.beale, fmin, x0, xmin, xmax )
  File "/export/sherpa/sherpa/optmethods/tests/test_optmethods.py", line 48, in tst_all
    x0, xmin, xmax, iprint=iprint)
  File "/export/sherpa/sherpa/optmethods/tests/test_optmethods.py", line 61, in tst
    self.assertEqualWithinTol( fval, fmin, self.tolerance )
  File "/export/sherpa/sherpa/utils/__init__.py", line 266, in assertEqualWithinTol
    self.assertFalse(numpy.any(sao_fcmp(first, second, tol)), msg)
AssertionError: True is not false

======================================================================
FAIL: test_box3d (sherpa.optmethods.tests.test_optmethods.test_optmethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/export/sherpa/sherpa/optmethods/tests/test_optmethods.py", line 143, in test_box3d
    self.tst_all( name, _tstoptfct.box3d, fmin, x0, xmin, xmax )
  File "/export/sherpa/sherpa/optmethods/tests/test_optmethods.py", line 48, in tst_all
    x0, xmin, xmax, iprint=iprint)
  File "/export/sherpa/sherpa/optmethods/tests/test_optmethods.py", line 61, in tst
    self.assertEqualWithinTol( fval, fmin, self.tolerance )
  File "/export/sherpa/sherpa/utils/__init__.py", line 266, in assertEqualWithinTol
    self.assertFalse(numpy.any(sao_fcmp(first, second, tol)), msg)
AssertionError: True is not false

======================================================================
FAIL: test_brown_badly_scaled (sherpa.optmethods.tests.test_optmethods.test_optmethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/export/sherpa/sherpa/optmethods/tests/test_optmethods.py", line 91, in test_brown_badly_scaled
    xmax )
  File "/export/sherpa/sherpa/optmethods/tests/test_optmethods.py", line 48, in tst_all
    x0, xmin, xmax, iprint=iprint)
  File "/export/sherpa/sherpa/optmethods/tests/test_optmethods.py", line 61, in tst
    self.assertEqualWithinTol( fval, fmin, self.tolerance )
  File "/export/sherpa/sherpa/utils/__init__.py", line 266, in assertEqualWithinTol
    self.assertFalse(numpy.any(sao_fcmp(first, second, tol)), msg)
AssertionError: True is not false

----------------------------------------------------------------------
Ran 26 tests in 5.195s