Tests: better diagnostic for a test failure
Since parvals is a tuple we can get less-than-useful diagnostic
information from pytest, such as

```
>       assert got.parvals == pytest.approx(expected['parvals'], rel=tol)
E       AssertionError: assert (1.7502017611...5752787318452) == approx([1.750...66 ± 2.0e-06])
E         (pytest_assertion plugin: representation of details failed: /tmp/marie-testing/local-install/ciao-4.15/ots/lib/python3.10/site-packages/_pytest/python_api.py:175: AttributeError: 'tuple' object has no attribute 'shape'.
E          Probably an object has a faulty __repr__.)
```