XSPEC: invalidate some combinations of XSPEC models. Fix #2420
While we can allow multiplying two additive models, it isn't really
sensible, and something XSPEC prevents. So make it harder to create
"invalid" model expressions for both additive models (prevent
multiplication and division) and multiplicative models (prevent
addition and subtraction).

There are other operations that could be removed from the
AdditiveModel class - e.g. mod and pow - but leave those for now.

There is a work-around: the current check is only on whether the
two models are instances of the relevant XSPEC class, but it does
not check for combined models. So this fails (when m1 is an instance
of sherpa.astro.xspec.XSapec, an additive model):

  >>> m1 * m1
  TypeError: Invalid operation: XSapec * XSapec

but we can trick the system into making one of the terms a
combination:

  >>> m1 * (m1 + 1)
  <BinaryOpModel model instance 'apec * (apec + 1.0)'>

Fixing this would complicate the code, so is it worth it?