model: add get_thawed_pars method
There are two changes

a) pars is now a property, so users can not set it

   This might cause a problem for some users, but if so then they are
   doing something rather strange / outside of Sherpa's design and a
   different approach would be warranted.

   However, it does stop people from doing something like

   >>> create_model_component("gauss1d", "mdl")
   >>> mdl.pars = [1]
   >>> mdl([1, 2, 3])
   AttributeError: 'int' object has no attribute 'val'

b) adds a get_thawed_pars method that returns the thawed parameters

   This mainly makes the internals a little cleaner, in particular
   in sherpa.fit where we take advantage of this cleanup to remove
   the internal calc_indices setting which was needed to map between
   the thawed parameters and the .pars field, but now we have a list
   of thawed parameters we don't need this indirection (the code could
   always have been written like this).

   At this point we do not include linked parameters in the return
   of get_thawed_pars, but it might not surprise you to find out that
   the plan is to change that!