Will only call for the calculation of the covariance matrix if the minuit_status.hesse_failed is False.  I learned this the hard way when I ran the latest bug report from a user as relayed to us by Nick.
WARNING: imaging routines will not be available,
failed to import sherpa.image.ds9_backend due to
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
read ARF file 18076.corr.arf
read RMF file 18076.rmf
read ARF (background) file 18076_bkg.arf
read RMF (background) file 18076_bkg.rmf
read background file 18076_bkg.pi
WARNING: data set 1 has associated backgrounds, but they have not been subtracted, nor have background models been set
Traceback (most recent call last):
  File "fit.py", line 44, in <module>
    fitme(method1, method2)
  File "fit.py", line 27, in fitme
    fit()
  File "<string>", line 1, in fit
  File "/export/sherpa/sherpa/astro/ui/utils.py", line 9261, in fit
    self._fit(id, *otherids, **kwargs)
  File "/export/sherpa/sherpa/astro/ui/utils.py", line 9365, in _fit
    res = f.fit(**kwargs)
  File "/export/sherpa/sherpa/fit.py", line 58, in run
    result = func(fit, *args, **kwargs)
  File "/export/sherpa/sherpa/fit.py", line 1111, in fit
    self.model.thawedparmaxes)
  File "/export/sherpa/sherpa/fit.py", line 913, in fit
    statargs, statkwargs)
  File "/export/sherpa/sherpa/optmethods/__init__.py", line 103, in fit
    output = self._optfunc(cb, pars, parmins, parmaxes, **self.config)
  File "/export/sherpa/sherpa/optmethods/optfcts.py", line 936, in midnight
    covar_matrix = numpy.array(myminuit.matrix(correlation=True))
  File "iminuit/_libiminuit.pyx", line 543, in iminuit._libiminuit.Minuit.matrix (iminuit/_libiminuit.cpp:7632)
RuntimeError: Covariance is not valid. May be the last Hesse call failed?